# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: statistics_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'statistics_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18statistics_service.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"1\n\rActionRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\"b\n\x0e\x41\x63tionResponse\x12\x0f\n\x07post_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12.\n\nupdated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2k\n\x11StatisticsService\x12*\n\x07\x41\x64\x64Like\x12\x0e.ActionRequest\x1a\x0f.ActionResponse\x12*\n\x07\x41\x64\x64View\x12\x0e.ActionRequest\x1a\x0f.ActionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statistics_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTIONREQUEST']._serialized_start=61
  _globals['_ACTIONREQUEST']._serialized_end=110
  _globals['_ACTIONRESPONSE']._serialized_start=112
  _globals['_ACTIONRESPONSE']._serialized_end=210
  _globals['_STATISTICSSERVICE']._serialized_start=212
  _globals['_STATISTICSSERVICE']._serialized_end=319
# @@protoc_insertion_point(module_scope)
