CREATE TABLE IF NOT EXISTS Posts (
    postId SERIAL PRIMARY KEY,
    userId SERIAL NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    isPrivate BOOLEAN NOT NULL DEFAULT FALSE,
    tags TEXT[],
    title TEXT NOT NULL,
    description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Comments (
    commentId SERIAL PRIMARY KEY,
    userId SERIAL NOT NULL,
    postId SERIAL NOT NULL REFERENCES Posts(postId) ON DELETE CASCADE,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description TEXT NOT NULL
);
