version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./user_service/postgres/initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
   
